
import numpy as np
from resemblyzer import VoiceEncoder

def test_embedding():
    print("Testing embedding extraction...")
    try:
        encoder = VoiceEncoder()
        
        # Simulate audio data as generated by speech_recognition_engine.py
        # 3 seconds of silence/noise
        duration = 1
        sample_rate = 16000
        frames_per_buffer = 1024
        total_frames = int(sample_rate / 1024 * duration) * 1024
        
        # Generate random int16 data (mocking microphone input)
        raw_int16 = np.random.randint(-32768, 32767, total_frames, dtype=np.int16)
        raw_bytes = raw_int16.tobytes()
        
        # Apply the transformation logic from speech_recognition_engine.py
        audio_int16 = np.frombuffer(raw_bytes, dtype=np.int16)
        audio_float = audio_int16.astype(np.float32) / 32768.0
        
        print(f"Audio shape: {audio_float.shape}")
        print(f"Audio dtype: {audio_float.dtype}")
        print(f"Audio min/max: {audio_float.min()}, {audio_float.max()}")
        
        embedding = encoder.embed_utterance(audio_float)
        print("Embedding extraction successful!")
        print(f"Embedding shape: {embedding.shape}")
        
    except Exception as e:
        print(f"Error caught: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    test_embedding()
